In [8]:
import numpy as np
import pandas as pd
from ucimlrepo import fetch_ucirepo 
  
# fetch dataset 
ionosphere = fetch_ucirepo(id=52) 
  
# data (as pandas dataframes) 
X = ionosphere.data.features 
y = ionosphere.data.targets 
  
# metadata 
print(ionosphere.metadata) 
  
# variable information 
print(ionosphere.variables) 


{'uci_id': 52, 'name': 'Ionosphere', 'repository_url': 'https://archive.ics.uci.edu/dataset/52/ionosphere', 'data_url': 'https://archive.ics.uci.edu/static/public/52/data.csv', 'abstract': 'Classification of radar returns from the ionosphere', 'area': 'Physics and Chemistry', 'tasks': ['Classification'], 'characteristics': ['Multivariate'], 'num_instances': 351, 'num_features': 34, 'feature_types': ['Integer', 'Real'], 'demographics': [], 'target_col': ['Class'], 'index_col': None, 'has_missing_values': 'no', 'missing_values_symbol': None, 'year_of_dataset_creation': 1989, 'last_updated': 'Sun Jan 01 1989', 'dataset_doi': '10.24432/C5W01B', 'creators': ['V. Sigillito', 'S. Wing', 'L. Hutton', 'K. Baker'], 'intro_paper': None, 'additional_info': {'summary': 'This radar data was collected by a system in Goose Bay, Labrador.  This system consists of a phased array of 16 high-frequency antennas with a total transmitted power on the order of 6.4 kilowatts.  See the paper for more details.  

In [17]:
X.duplicated().sum()  # Check for missing values in each column

np.int64(1)

In [ ]:
#array
array = X.values
print(array)

point1 = array[0,:]
point2 = array[1,:]
point3 = array[2,:]

#p=1
dist01_2 = np.linalg.norm(point1 - point2,1)
dist01_3 = np.linalg.norm(point1 - point3,1)

#p=2
dist1_2 = np.linalg.norm(point1 - point2)
dist1_3 = np.linalg.norm(point1 - point3)

#p=inf
dist11_2 = np.linalg.norm(point1 - point2,np.inf)
dist11_3 = np.linalg.norm(point1 - point3,np.inf)

#print results
print(dist1_2)
print(dist1_3)
print(dist01_2)
print(dist01_3)
print(dist11_2)
print(dist11_3)


[[ 1.       0.       0.99539 ... -0.54487  0.18641 -0.453  ]
 [ 1.       0.       1.      ... -0.06288 -0.13738 -0.02447]
 [ 1.       0.       1.      ... -0.2418   0.56045 -0.38238]
 ...
 [ 1.       0.       0.94701 ...  0.00442  0.92697 -0.00577]
 [ 1.       0.       0.90608 ... -0.03757  0.87403 -0.16243]
 [ 1.       0.       0.8471  ... -0.06678  0.85764 -0.06151]]
2.7763589251571923
1.1697276018372824
13.080950000000001
5.359709999999999
1.12221
0.45772


In [ ]:
# Make matrix distance (50, 50)
def tinh_chuan(dataset): 
    Distance_chuan_1 = np.zeros((50, 50))
    Distance_chuan_2 = np.zeros((50, 50))
    Distance_chuan_vocung = np.zeros((50, 50))
    for i in range(50):
        for j in range(i+1, 50):
            point1 = array[i,:]
            point2 = array[j,:]

            #p=1
            dist01_2 = np.linalg.norm(point1 - point2,1)
            Distance_chuan_1[i][j] = dist01_2
            Distance_chuan_1[j][i] = dist01_2

            #p=2
            dist1_2 = np.linalg.norm(point1 - point2)
            Distance_chuan_2[i][j] = dist1_2
            Distance_chuan_2[j][i] = dist1_2

            #p=inf
            

    Distance_chuan_1 = pd.DataFrame(Distance_chuan_1)
    Distance_chuan_2 = pd.DataFrame(Distance_chuan_2)
    Distance_chuan_vocung = pd.DataFrame(Distance_chuan_vocung)

0         1         2         3         4         5         6   \
0    0.00000  13.08095   5.35971  21.05729   6.21387  15.16631   7.57704   
1   13.08095   0.00000  15.80038  20.76960  11.52616  12.58796  12.28109   
2    5.35971  15.80038   0.00000  20.30478   8.50424  14.24844  11.57535   
3   21.05729  20.76960  20.30478   0.00000  20.75218  17.81826  24.99635   
4    6.21387  11.52616   8.50424  20.75218   0.00000  11.78266   6.42595   
5   15.16631  12.58796  14.24844  17.81826  11.78266   0.00000  17.61223   
6    7.57704  12.28109  11.57535  24.99635   6.42595  17.61223   0.00000   
7   22.28699  22.63900  21.16584  15.73696  22.27638  15.66824  26.06633   
8    5.81361  16.54506   7.82230  25.08336   9.06074  20.15200   6.56417   
9   17.20169  14.54198  16.08502  19.09482  14.07940   5.57928  19.53089   
10   7.06033  16.56300   9.69796  26.54798  10.21672  21.38354   4.67139   
11  16.25809  23.70878  15.70286  27.23990  19.77926  28.16168  17.94391   
12   6.37224  17.69897   6.70095  24.51229   9.48617  20.17001   9.35174   
13  14.07453  21.91832  11.98718  21.12056  17.99574  22.61724  18.29209   
14  14.98318  24.34825  10.30557  21.50073  18.73183  20.11953  21.34650   
15  18.11757  12.67514  18.04060  17.95398  16.89034  14.04062  20.75509   
16  10.99360  20.26597   6.22373  20.56567  14.66491  16.03889  17.17936   
17  34.53319  36.99534  33.62230  41.34490  33.84704  31.38644  33.59039   
18  12.67162  19.97037   9.88059  18.56813  14.82501  12.47461  18.12408   
19  30.18582  30.94441  27.62785  25.90905  30.45773  26.66625  34.24420   
20   6.24754  17.83165   5.71581  23.79321  10.79553  19.13177  11.66314   
21  30.92729  26.03694  30.89688  22.82630  27.88674  21.24780  31.43447   
22   7.76043  16.78962   3.47066  19.89968  11.05576  13.63586  13.53111   
23  27.62719  29.96502  26.54472  27.79156  27.26984  21.82590  30.23293   
24   6.26550  17.14547   3.72611  21.60239   9.69389  16.77697  12.08250   
25  16.24697  22.28624  17.64422  32.56844  19.85542  31.02224  14.24663   
26   8.25909  16.12232  11.04488  23.79508  10.97748  20.17912   7.10401   
27  25.77937  24.57698  25.93152  25.15664  24.80486  20.35018  25.44075   
28  21.26855  30.63362  16.65062  21.81958  24.91842  26.39802  27.59531   
29  27.85635  31.38808  28.19738  26.94540  29.42508  31.56526  27.76597   
30   8.44451  20.04280   8.84000  25.25426  11.77962  22.27348  11.28413   
31  20.84771  24.96278  19.49584  21.91130  23.22176  28.51568  22.55585   
32   4.18114  15.47241   5.39883  22.96497   7.45171  17.64553   7.47878   
33  10.57017  18.61860  10.46804  22.37266  12.61866  17.76778  13.88467   
34  11.94792  21.13621  10.09461  22.44323  15.76749  20.86209  16.65596   
35  19.76191  25.97102  17.79122  22.72924  23.08336  26.33956  23.33779   
36   8.78373  18.69414   4.73220  22.09176  12.45582  17.30544  14.86127   
37  29.15677  27.83860  26.93828  25.74690  27.91056  23.65826  32.47167   
38  10.47754  19.80253   5.85357  20.60847  14.08055  15.38787  16.63238   
39  12.92207  21.84682   8.69736  20.62994  15.50762  17.07672  18.10913   
40  15.50779  22.70350  13.48098  19.43860  16.88588  18.33580  19.61779   
41  26.84853  26.61692  26.12440  30.66386  25.24436  25.91510  25.34873   
42  15.40607  20.28314  13.66118  18.04686  14.88660  14.45434  18.63649   
43  19.81221  26.21146  18.89458  26.25282  22.87998  27.73236  22.01471   
44   6.32025  17.33330   7.53900  25.16296   9.56442  20.67142   6.74603   
45  22.58643  19.99236  22.89582  28.67772  21.35254  15.67980  23.75111   
46   6.06466  17.97123   5.52207  23.38175  10.17651  19.03413  11.58970   
47  15.98462  17.53049  15.88161  19.61183  15.35159  15.88133  19.15362   
48   7.74504  17.89603   4.16871  21.73987  11.46505  16.68943  13.66274   
49  21.06072  18.96035  19.98939  22.64283  18.71277  13.27289  22.72214   

          7         8         9   ...        40        41        42        43  \
0   22.28699   5.81361  17.20169  ...  15.50779  26.

## Bài 2:

### Độ đo overlap

In [ ]:
import pandas as pd
from sklearn.neighbors import NearestNeighbors

# Load dữ liệu
df = pd.read_csv("kdd1998.csv")  # Cập nhật đúng tên file

# Chọn các cột số để tính toán (bỏ cột phân loại hoặc không liên quan)
numerical_cols = df.select_dtypes(include=['number']).columns
data = df[numerical_cols].fillna(0)  # Xử lý giá trị thiếu nếu có


In [ ]:
# Khởi tạo mô hình KNN
k = 5  # Số láng giềng cần tìm
knn = NearestNeighbors(n_neighbors=k, metric='euclidean')  # Có thể đổi sang 'manhattan' hoặc 'cosine'

# Huấn luyện mô hình
knn.fit(data)

# Chọn một điểm để tìm hàng xóm gần nhất (ví dụ: hàng đầu tiên)
sample_point = data.iloc[0].values.reshape(1, -1)

# Tìm k hàng xóm gần nhất
distances, indices = knn.kneighbors(sample_point)

# In ra kết quả
print("Các hàng xóm gần nhất:", indices)
print("Khoảng cách tương ứng:", distances)


### Độ đo tần suất xuất hiện ngược

In [ ]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer

# Giả sử KDD 1998 có cột văn bản tên là 'text_column'
df = pd.read_csv("kdd1998.csv")  # Load dữ liệu
texts = df["text_column"].astype(str)  # Chuyển về dạng chuỗi nếu cần

# Khởi tạo Vectorizer
vectorizer = TfidfVectorizer(use_idf=True)
tfidf_matrix = vectorizer.fit_transform(texts)

# Lấy giá trị IDF của từng từ
idf_values = dict(zip(vectorizer.get_feature_names_out(), vectorizer.idf_))

# In một số từ và IDF của chúng
for word, idf in list(idf_values.items())[:10]:  # Hiển thị 10 từ đầu tiên
    print(f"Từ: {word}, IDF: {idf}")
