# Mục 1

In [2]:
# Load dữ liệu thành DataFrame Pandas
import pandas as pd
import numpy as np
from sklearn import preprocessing

df = pd.read_csv('data.csv')

# đặt lại index
df = df.set_index('ID')
df

First Name Last Name   Age Gender Department   Salary Date of Joining
ID                                                                      
1        John       Doe  25.0      M      Sales  50000.0      01/01/2020
2        Jane     Smith  30.0      F  Marketing  60000.0      06/01/2018
3         Bod   Johnson  45.0      M         HR  70000.0      09/01/2016
4       Alice  Williams  33.0      F         IT  80000.0      02/01/2017
5       James     Brown  27.0      M      Sales  55000.0      03/01/2019
6       Sarah       Lee   NaN      F  Marketing  65000.0      12/01/2018
7     Michael     Davis  39.0      M         HR      NaN      08/01/2015
8       Susan    Miller  42.0      F         IT  90000.0      11/01/2014
9       David    Wilson  28.0      M      Sales  60000.0      05/01/2020
10      Emily     Brown  35.0      F  Marketing  55000.0      04/01/2017
11       John       Doe  25.0      M      Sales  50000.0      01/01/2020
12       John       Doe  25.0      M      Sales  50000.0      01/01/2020

In [3]:
#2. Kiểm tra các giá trị missing
print(df.isnull().sum())
# làm đầy các giá trị missing bằng giá trị trung bình chỉ cho các cột numeric
df.fillna(df.select_dtypes(include=np.number).mean(), inplace=True)

First Name         0
Last Name          0
Age                1
Gender             0
Department         0
Salary             1
Date of Joining    0
dtype: int64


In [4]:
#3. Kiểm tra giá trị giống nhau
print(df.duplicated().sum())
# loại bỏ các dòng giống nhau
df = df.drop_duplicates()
df

2


First Name Last Name        Age Gender Department        Salary  \
ID                                                                   
1        John       Doe  25.000000      M      Sales  50000.000000   
2        Jane     Smith  30.000000      F  Marketing  60000.000000   
3         Bod   Johnson  45.000000      M         HR  70000.000000   
4       Alice  Williams  33.000000      F         IT  80000.000000   
5       James     Brown  27.000000      M      Sales  55000.000000   
6       Sarah       Lee  32.181818      F  Marketing  65000.000000   
7     Michael     Davis  39.000000      M         HR  62272.727273   
8       Susan    Miller  42.000000      F         IT  90000.000000   
9       David    Wilson  28.000000      M      Sales  60000.000000   
10      Emily     Brown  35.000000      F  Marketing  55000.000000   

   Date of Joining  
ID                  
1       01/01/2020  
2       06/01/2018  
3       09/01/2016  
4       02/01/2017  
5       03/01/2019  
6       12/01/2018  
7       08/01/2015  
8       11/01/2014  
9       05/01/2020  
10      04/01/2017

In [5]:
# Mã hóa dữ liệu categorical
df = pd.get_dummies(df, columns=['Gender', 'Department'])
for column in df.columns:
    if df[column].dtype == bool:
        df[column] = df[column].astype(int)

In [6]:
# Xử lý dữ liệu datetime
## Chuyển cột date thành một đối tượng datetime
df['Date of Joining'] = pd.to_datetime(df['Date of Joining'])
## Extract month and day of week from date column
df['month'] = df['Date of Joining'].dt.month
df['day_of_week'] = df['Date of Joining'].dt.day_name()
## Drop the original 'Date' column
df = df.drop('Date of Joining', axis=1)
df

First Name Last Name        Age        Salary  Gender_F  Gender_M  \
ID                                                                     
1        John       Doe  25.000000  50000.000000         0         1   
2        Jane     Smith  30.000000  60000.000000         1         0   
3         Bod   Johnson  45.000000  70000.000000         0         1   
4       Alice  Williams  33.000000  80000.000000         1         0   
5       James     Brown  27.000000  55000.000000         0         1   
6       Sarah       Lee  32.181818  65000.000000         1         0   
7     Michael     Davis  39.000000  62272.727273         0         1   
8       Susan    Miller  42.000000  90000.000000         1         0   
9       David    Wilson  28.000000  60000.000000         0         1   
10      Emily     Brown  35.000000  55000.000000         1         0   

    Department_HR  Department_IT  Department_Marketing  Department_Sales  \
ID                                                                         
1               0              0                     0                 1   
2               0              0                     1                 0   
3               1              0                     0                 0   
4               0              1                     0                 0   
5               0              0                     0                 1   
6               0              0                     1                 0   
7               1              0                     0                 0   
8               0              1                     0                 0   
9               0              0                     0                 1   
10              0              0                     1                 0   

    month day_of_week  
ID                     
1       1   Wednesday  
2       6      Friday  
3       9    Thursday  
4       2   Wednesday  
5       3      Friday  
6      12    Saturday  
7       8    Saturday  
8      11    Saturday  
9       5      Friday  
10      4    Saturday

In [7]:
# xử lý các giá trị ngoại lai
# chuẩn hóa và scale dữ liệu
df1 = df.drop(['First Name', 'Last Name', 'day_of_week'], axis=1)
array = df1.values

### Sử dụng RobustScaler() để loại bỏ những giá trị ngoại lai
scaler = preprocessing.RobustScaler()
robust_df = scaler.fit_transform(array)
robust_df = pd.DataFrame(robust_df)
print(robust_df)

### Chuẩn hóa dữ liệu bằng phương pháp z-score (Standard)
scaler = preprocessing.StandardScaler()
standard = scaler.fit_transform(array)
standard_df = pd.DataFrame(standard, index=df.index)
print('Chuan hoa du lieu:\n', standard_df)

### Scale dữ liệu bằng phương pháp minmax
scaler = preprocessing.MinMaxScaler()
minmax = scaler.fit_transform(array)
minmax_df = pd.DataFrame(minmax, index=df.index)
print('Scaling dữ liệu:\n', minmax_df)

          0         1    2    3    4    5         6         7         8
0 -0.799043 -0.890909 -0.5  0.5  0.0  0.0  0.000000  1.333333 -0.818182
1 -0.272727 -0.090909  0.5 -0.5  0.0  0.0  1.333333  0.000000  0.090909
2  1.306220  0.709091 -0.5  0.5  1.0  0.0  0.000000  0.000000  0.636364
3  0.043062  1.509091  0.5 -0.5  0.0  1.0  0.000000  0.000000 -0.636364
4 -0.588517 -0.490909 -0.5  0.5  0.0  0.0  0.000000  1.333333 -0.454545
5 -0.043062  0.309091  0.5 -0.5  0.0  0.0  1.333333  0.000000  1.181818
6  0.674641  0.090909 -0.5  0.5  1.0  0.0  0.000000  0.000000  0.454545
7  0.990431  2.309091  0.5 -0.5  0.0  1.0  0.000000  0.000000  1.000000
8 -0.483254 -0.090909 -0.5  0.5  0.0  0.0  0.000000  1.333333 -0.090909
9  0.253589 -0.490909  0.5 -0.5  0.0  0.0  1.333333  0.000000 -0.272727
Chuan hoa du lieu:
            0         1    2    3    4    5         6         7         8
ID                                                                      
1  -1.369782 -1.264391 -1.0  1.0 -0.5 -0.5

In [8]:
###### 10 equi-width ranges với tất cả các cột của standard_df
df2 = standard_df.copy()
for i in df2.columns:
    df2[f'equi_width_column_{i}'] = pd.cut(x=df2[i], bins=10)
print(f'Roi rac hoa cot cac cot bang 10 equi-width ranges:\n', df2)

Roi rac hoa cot cac cot bang 10 equi-width ranges:
            0         1    2    3    4    5         6         7         8  \
ID                                                                         
1  -1.369782 -1.264391 -1.0  1.0 -0.5 -0.5 -0.654654  1.527525 -1.420508   
2  -0.575077 -0.405854  1.0 -1.0 -0.5 -0.5  1.527525 -0.654654 -0.027853   
3   1.809037  0.452683 -1.0  1.0  2.0 -0.5 -0.654654 -0.654654  0.807740   
4  -0.098254  1.311220  1.0 -1.0 -0.5  2.0 -0.654654 -0.654654 -1.141977   
5  -1.051900 -0.835122 -1.0  1.0 -0.5 -0.5 -0.654654  1.527525 -0.863446   
6  -0.228297  0.023415  1.0 -1.0 -0.5 -0.5  1.527525 -0.654654  1.643333   
7   0.855391 -0.210732 -1.0  1.0  2.0 -0.5 -0.654654 -0.654654  0.529209   
8   1.332214  2.169757  1.0 -1.0 -0.5  2.0 -0.654654 -0.654654  1.364802   
9  -0.892959 -0.405854 -1.0  1.0 -0.5 -0.5 -0.654654  1.527525 -0.306384   
10  0.219627 -0.835122  1.0 -1.0 -0.5 -0.5  1.527525 -0.654654 -0.584915   

   equi_width_column_0 equi_width_c

In [9]:
###### 10 equi-depth ranges với tất cả các cột của standard_df
df3 = standard_df.copy()
for i in df3.columns:
    df3[f'equi_depth_column_{i}'] = pd.qcut(x=df3[i], q=10, duplicates='drop')
print(f'Roi rac hoa cot cac cot bang 10 equi-depth ranges:\n', df3)

Roi rac hoa cot cac cot bang 10 equi-depth ranges:
            0         1    2    3    4    5         6         7         8  \
ID                                                                         
1  -1.369782 -1.264391 -1.0  1.0 -0.5 -0.5 -0.654654  1.527525 -1.420508   
2  -0.575077 -0.405854  1.0 -1.0 -0.5 -0.5  1.527525 -0.654654 -0.027853   
3   1.809037  0.452683 -1.0  1.0  2.0 -0.5 -0.654654 -0.654654  0.807740   
4  -0.098254  1.311220  1.0 -1.0 -0.5  2.0 -0.654654 -0.654654 -1.141977   
5  -1.051900 -0.835122 -1.0  1.0 -0.5 -0.5 -0.654654  1.527525 -0.863446   
6  -0.228297  0.023415  1.0 -1.0 -0.5 -0.5  1.527525 -0.654654  1.643333   
7   0.855391 -0.210732 -1.0  1.0  2.0 -0.5 -0.654654 -0.654654  0.529209   
8   1.332214  2.169757  1.0 -1.0 -0.5  2.0 -0.654654 -0.654654  1.364802   
9  -0.892959 -0.405854 -1.0  1.0 -0.5 -0.5 -0.654654  1.527525 -0.306384   
10  0.219627 -0.835122  1.0 -1.0 -0.5 -0.5  1.527525 -0.654654 -0.584915   

   equi_depth_column_0 equi_depth_c

# Mục 2

In [10]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import KBinsDiscretizer

df = pd.read_csv('arrhythmia.data', delimiter=',', header=None, na_values='?')
df

0    1    2    3    4    5    6    7    8    9    ...  270   271   272  \
0     75    0  190   80   91  193  371  174  121  -16  ...  0.0   9.0  -0.9   
1     56    1  165   64   81  174  401  149   39   25  ...  0.0   8.5   0.0   
2     54    0  172   95  138  163  386  185  102   96  ...  0.0   9.5  -2.4   
3     55    0  175   94  100  202  380  179  143   28  ...  0.0  12.2  -2.2   
4     75    0  190   80   88  181  360  177  103  -16  ...  0.0  13.1  -3.6   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   ...   ...   
447   53    1  160   70   80  199  382  154  117  -37  ...  0.0   4.3  -5.0   
448   37    0  190   85  100  137  361  201   73   86  ...  0.0  15.6  -1.6   
449   36    0  166   68  108  176  365  194  116  -85  ...  0.0  16.3 -28.6   
450   32    1  155   55   93  106  386  218   63   54  ... -0.4  12.0  -0.7   
451   78    1  160   70   79  127  364  138   78   28  ...  0.0  10.4  -1.8   

     273  274  275  276   277   278  279  
0    0.0  0.0  0.9  2.9  23.3  49.4    8  
1    0.0  0.0  0.2  2.1  20.4  38.8    6  
2    0.0  0.0  0.3  3.4  12.3  49.0   10  
3    0.0  0.0  0.4  2.6  34.6  61.6    1  
4    0.0  0.0 -0.1  3.9  25.4  62.8    7  
..   ...  ...  ...  ...   ...   ...  ...  
447  0.0  0.0  0.7  0.6  -4.4  -0.5    1  
448  0.0  0.0  0.4  2.4  38.0  62.4   10  
449  0.0  0.0  1.5  1.0 -44.2 -33.2    2  
450  0.0  0.0  0.5  2.4  25.0  46.6    1  
451  0.0  0.0  0.5  1.6  21.3  32.8    1  

[452 rows x 280 columns]

In [11]:
#2. Kiểm tra các giá trị missing
print(df.isnull().sum())
# làm đầy các giá trị missing bằng giá trị trung bình chỉ cho các cột numeric
df.fillna(df.mean(), inplace=True)

0      0
1      0
2      0
3      0
4      0
      ..
275    0
276    0
277    0
278    0
279    0
Length: 280, dtype: int64


In [12]:
#3. Kiểm tra giá trị giống nhau
print(df.duplicated().sum())

0


In [13]:
# xử lý các giá trị ngoại lai
# chuẩn hóa và scale dữ liệu
array = df.values
print(array)

### Sử dụng RobustScaler() để loại bỏ những giá trị ngoại lai
scaler = preprocessing.RobustScaler()
robust_df = scaler.fit_transform(array)
robust_df = pd.DataFrame(robust_df)

### Chuẩn hóa dữ liệu bằng phương pháp z-score (Standard)
scaler = preprocessing.StandardScaler()
standard = scaler.fit_transform(array)
standard_df = pd.DataFrame(standard)
print('Chuan hoa du lieu:\n', standard_df)

### Scale dữ liệu bằng phương pháp minmax
scaler = preprocessing.MinMaxScaler()
minmax = scaler.fit_transform(array)
minmax_df = pd.DataFrame(minmax)
print('Scaling dữ liệu:\n', minmax_df)

[[ 75.    0.  190.  ...  23.3  49.4   8. ]
 [ 56.    1.  165.  ...  20.4  38.8   6. ]
 [ 54.    0.  172.  ...  12.3  49.   10. ]
 ...
 [ 36.    0.  166.  ... -44.2 -33.2   2. ]
 [ 32.    1.  155.  ...  25.   46.6   1. ]
 [ 78.    1.  160.  ...  21.3  32.8   1. ]]
Chuan hoa du lieu:
           0         1         2         3         4         5         6    \
0    1.734439 -1.107520  0.641327  0.713814  0.135505  0.844945  0.113709   
1    0.579312  0.902918 -0.031998 -0.251644 -0.516072  0.420769  1.013301   
2    0.457720 -1.107520  0.156533  1.618932  3.197915  0.175193  0.563505   
3    0.518516 -1.107520  0.237332  1.558590  0.721924  1.045871  0.383587   
4    1.734439 -1.107520  0.641327  0.713814 -0.059968  0.577044 -0.216141   
..        ...       ...       ...       ...       ...       ...       ...   
447  0.396924  0.902918 -0.166663  0.110403 -0.581229  0.978896  0.443560   
448 -0.575815 -1.107520  0.641327  1.015520  0.721924 -0.405260 -0.186154   
449 -0.636611 -1.107520

In [14]:
###### 10 equi-width ranges với tất cả các cột của standard_df
df2 = standard_df.copy()
for i in df2.columns:
    df2[f'equi_width_column_{i}'] = pd.cut(x=df2[i], bins=10)
print(f'Roi rac hoa cot cac cot bang 10 equi-width ranges:\n', df2)

Roi rac hoa cot cac cot bang 10 equi-width ranges:
             0         1         2         3         4         5         6  \
0    1.734439 -1.107520  0.641327  0.713814  0.135505  0.844945  0.113709   
1    0.579312  0.902918 -0.031998 -0.251644 -0.516072  0.420769  1.013301   
2    0.457720 -1.107520  0.156533  1.618932  3.197915  0.175193  0.563505   
3    0.518516 -1.107520  0.237332  1.558590  0.721924  1.045871  0.383587   
4    1.734439 -1.107520  0.641327  0.713814 -0.059968  0.577044 -0.216141   
..        ...       ...       ...       ...       ...       ...       ...   
447  0.396924  0.902918 -0.166663  0.110403 -0.581229  0.978896  0.443560   
448 -0.575815 -1.107520  0.641327  1.015520  0.721924 -0.405260 -0.186154   
449 -0.636611 -1.107520 -0.005065 -0.010279  1.243185  0.465419 -0.066209   
450 -0.879796  0.902918 -0.301328 -0.794714  0.265820 -1.097337  0.563505   
451  1.916828  0.902918 -0.166663  0.110403 -0.646387 -0.628511 -0.096195   

            7         8

In [15]:
###### 10 equi-depth ranges với tất cả các cột của standard_df
df3 = standard_df.copy()
for i in df3.columns:
    df3[f'equi_depth_column_{i}'] = pd.qcut(x=df3[i], q=10, duplicates='drop')
print(f'Roi rac hoa cot cac cot bang 10 equi-depth ranges:\n', df3)

Roi rac hoa cot cac cot bang 10 equi-depth ranges:
             0         1         2         3         4         5         6  \
0    1.734439 -1.107520  0.641327  0.713814  0.135505  0.844945  0.113709   
1    0.579312  0.902918 -0.031998 -0.251644 -0.516072  0.420769  1.013301   
2    0.457720 -1.107520  0.156533  1.618932  3.197915  0.175193  0.563505   
3    0.518516 -1.107520  0.237332  1.558590  0.721924  1.045871  0.383587   
4    1.734439 -1.107520  0.641327  0.713814 -0.059968  0.577044 -0.216141   
..        ...       ...       ...       ...       ...       ...       ...   
447  0.396924  0.902918 -0.166663  0.110403 -0.581229  0.978896  0.443560   
448 -0.575815 -1.107520  0.641327  1.015520  0.721924 -0.405260 -0.186154   
449 -0.636611 -1.107520 -0.005065 -0.010279  1.243185  0.465419 -0.066209   
450 -0.879796  0.902918 -0.301328 -0.794714  0.265820 -1.097337  0.563505   
451  1.916828  0.902918 -0.166663  0.110403 -0.646387 -0.628511 -0.096195   

            7         8

# Mục 3

In [16]:
pip install ucimlrepo

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [17]:
from ucimlrepo import fetch_ucirepo

# fetch dataset
musk_version_2 = fetch_ucirepo(id=75)

# data (as pandas dataframes)
X = musk_version_2.data.features
y = musk_version_2.data.targets

# metadata
print(musk_version_2.metadata)

# variable information
print(musk_version_2.variables)


{'uci_id': 75, 'name': 'Musk (Version 2)', 'repository_url': 'https://archive.ics.uci.edu/dataset/75/musk+version+2', 'data_url': 'https://archive.ics.uci.edu/static/public/75/data.csv', 'abstract': 'The goal is to learn to predict whether new molecules will be musks or non-musks', 'area': 'Physics and Chemistry', 'tasks': ['Classification'], 'characteristics': ['Multivariate'], 'num_instances': 6598, 'num_features': 166, 'feature_types': ['Integer'], 'demographics': [], 'target_col': ['class'], 'index_col': ['molecule_name', 'conformation_name'], 'has_missing_values': 'no', 'missing_values_symbol': None, 'year_of_dataset_creation': 1994, 'last_updated': 'Sat Mar 16 2024', 'dataset_doi': '10.24432/C51608', 'creators': ['David Chapman', 'Ajay Jain'], 'intro_paper': None, 'additional_info': {'summary': 'This dataset describes a set of 102 molecules of which 39 are judged by human experts to be musks and the remaining 63 molecules are judged to be non-musks.  The goal is to learn to predi

In [18]:
# Apply PCA into above dataset
from sklearn.decomposition import PCA
pca = PCA(n_components=2)
principalComponents = pca.fit_transform(X)
principalDf = pd.DataFrame(data = principalComponents
             , columns = ['principal component 1', 'principal component 2'])
X.dtypes.unique()

array([dtype('int64')], dtype=object)

In [19]:
# report the eigenvectors and eigenvalues
print("Eigenvalues:", pca.explained_variance_)  # Access eigenvalues using explained_variance_
print("Eigenvectors:", pca.components_)

Eigenvalues: [456051.03646811 257892.78359708]
Eigenvectors: [[-0.00297138 -0.07067551 -0.07919386  0.07636567  0.002569   -0.03854542
   0.15457415 -0.03082978  0.13909506 -0.07074886  0.01666866  0.02851486
  -0.01180712 -0.02136987 -0.0083431  -0.00345123  0.14344556 -0.00664528
   0.0141755  -0.03274181  0.07731929  0.13837659  0.1216251  -0.12295964
  -0.13548821  0.12121699  0.08258056  0.05663292  0.03472125 -0.15637469
  -0.00231013 -0.01401714  0.05123079 -0.12758364  0.08527464 -0.01024635
   0.03341853  0.07598349 -0.08346349  0.06823959 -0.09628692 -0.01112667
  -0.03557194 -0.00048187 -0.00634286  0.01315843  0.01907625  0.08202165
  -0.02063837 -0.06012866  0.0439804   0.13908176  0.13966061  0.01252173
  -0.06328565  0.04858638  0.14487146 -0.02406349  0.00934473 -0.11827492
   0.08800078 -0.05130579  0.00651246 -0.15743875  0.08391587 -0.00615454
  -0.00376085 -0.02188955 -0.05143767 -0.02068033 -0.08934383 -0.07837137
   0.00823084 -0.00716006 -0.02863575  0.00067546  

In [30]:
# make an example for LSA
from sklearn.decomposition import TruncatedSVD
from sklearn.feature_extraction.text import TfidfVectorizer

# Danh sách văn bản mẫu
documents = [
    "Chó là loài động vật trung thành.",
    "Mèo là loài động vật thích leo trèo.",
    "Người nuôi chó thường dẫn chúng đi dạo.",
    "Người nuôi mèo thường để chúng ở nhà.",
    "Tôi thích nuôi chó vì chúng trung thành.",
    "Tôi thích nuôi mèo vì chúng dễ thương.",
]

# Chuyển đổi văn bản thành ma trận TF-IDF
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(documents)

# Xem danh sách các từ đặc trưng
print("Từ đặc trưng:", vectorizer.get_feature_names_out())


Từ đặc trưng: ['chó' 'chúng' 'dạo' 'dẫn' 'dễ' 'leo' 'loài' 'là' 'mèo' 'người' 'nhà'
 'nuôi' 'thành' 'thích' 'thương' 'thường' 'trung' 'trèo' 'tôi' 'vì' 'vật'
 'đi' 'để' 'động']


In [31]:
# Áp dụng LSA với 2 chủ đề (2 thành phần chính)
lsa = TruncatedSVD(n_components=3)
X_lsa = lsa.fit_transform(X)

# Hiển thị ma trận sau khi giảm chiều
print("Ma trận LSA:\n", X_lsa)


Ma trận LSA:
 [[ 0.58544235  0.65741269 -0.20873329]
 [ 0.50675186  0.61589077 -0.25743977]
 [ 0.48803701 -0.49065853 -0.48190838]
 [ 0.48930453 -0.52983519 -0.42477703]
 [ 0.76977526 -0.03745646  0.4305823 ]
 [ 0.64227864 -0.26380713  0.56710937]]
