In [35]:
import numpy as np
import pandas as pd
from ucimlrepo import fetch_ucirepo 
  
# fetch dataset 
ionosphere = fetch_ucirepo(id=52) 
  
# data (as pandas dataframes) 
X = ionosphere.data.features 
y = ionosphere.data.targets 
  
# metadata 
print(ionosphere.metadata) 
  
# variable information 
print(ionosphere.variables) 

{'uci_id': 52, 'name': 'Ionosphere', 'repository_url': 'https://archive.ics.uci.edu/dataset/52/ionosphere', 'data_url': 'https://archive.ics.uci.edu/static/public/52/data.csv', 'abstract': 'Classification of radar returns from the ionosphere', 'area': 'Physics and Chemistry', 'tasks': ['Classification'], 'characteristics': ['Multivariate'], 'num_instances': 351, 'num_features': 34, 'feature_types': ['Integer', 'Real'], 'demographics': [], 'target_col': ['Class'], 'index_col': None, 'has_missing_values': 'no', 'missing_values_symbol': None, 'year_of_dataset_creation': 1989, 'last_updated': 'Sun Jan 01 1989', 'dataset_doi': '10.24432/C5W01B', 'creators': ['V. Sigillito', 'S. Wing', 'L. Hutton', 'K. Baker'], 'intro_paper': None, 'additional_info': {'summary': 'This radar data was collected by a system in Goose Bay, Labrador.  This system consists of a phased array of 16 high-frequency antennas with a total transmitted power on the order of 6.4 kilowatts.  See the paper for more details.  

In [36]:
# Kiểm tra giá trị khuyết
print(X.isnull().sum())

Attribute1     0
Attribute2     0
Attribute3     0
Attribute4     0
Attribute5     0
Attribute6     0
Attribute7     0
Attribute8     0
Attribute9     0
Attribute10    0
Attribute11    0
Attribute12    0
Attribute13    0
Attribute14    0
Attribute15    0
Attribute16    0
Attribute17    0
Attribute18    0
Attribute19    0
Attribute20    0
Attribute21    0
Attribute22    0
Attribute23    0
Attribute24    0
Attribute25    0
Attribute26    0
Attribute27    0
Attribute28    0
Attribute29    0
Attribute30    0
Attribute31    0
Attribute32    0
Attribute33    0
Attribute34    0
dtype: int64


In [37]:
# Kiểm tra giá trị trùng lặp và xóa bỏ chúng
print("Số dòng trùng lặp:", X.duplicated().sum())
X = X.drop_duplicates()
X = X.reset_index(drop=True)
X

Số dòng trùng lặp: 1


Attribute1  Attribute2  Attribute3  Attribute4  Attribute5  Attribute6  \
0             1           0     0.99539    -0.05889     0.85243     0.02306   
1             1           0     1.00000    -0.18829     0.93035    -0.36156   
2             1           0     1.00000    -0.03365     1.00000     0.00485   
3             1           0     1.00000    -0.45161     1.00000     1.00000   
4             1           0     1.00000    -0.02401     0.94140     0.06531   
..          ...         ...         ...         ...         ...         ...   
345           1           0     0.83508     0.08298     0.73739    -0.14706   
346           1           0     0.95113     0.00419     0.95183    -0.02723   
347           1           0     0.94701    -0.00034     0.93207    -0.03227   
348           1           0     0.90608    -0.01657     0.98122    -0.01989   
349           1           0     0.84710     0.13533     0.73638    -0.06151   

     Attribute7  Attribute8  Attribute9  Attribute10  ...  Attribute25  \
0       0.83398    -0.37708     1.00000      0.03760  ...      0.56811   
1      -0.10868    -0.93597     1.00000     -0.04549  ...     -0.20332   
2       1.00000    -0.12062     0.88965      0.01198  ...      0.57528   
3       0.71216    -1.00000     0.00000      0.00000  ...      1.00000   
4       0.92106    -0.23255     0.77152     -0.16399  ...      0.03286   
..          ...         ...         ...          ...  ...          ...   
345     0.84349    -0.05567     0.90441     -0.04622  ...      0.95378   
346     0.93438    -0.01920     0.94590      0.01606  ...      0.94520   
347     0.95177    -0.03431     0.95584      0.02446  ...      0.93988   
348     0.95691    -0.03646     0.85746      0.00110  ...      0.91050   
349     0.87873     0.08260     0.88928     -0.09139  ...      0.86467   

     Attribute26  Attribute27  Attribute28  Attribute29  Attribute30  \
0       -0.51171      0.41078     -0.46168      0.21266     -0.34090   
1       -0.26569     -0.20468     -0.18401     -0.19040     -0.11593   
2       -0.40220      0.58984     -0.22145      0.43100     -0.17365   
3        0.90695      0.51613      1.00000      1.00000     -0.20099   
4       -0.65158      0.13290     -0.53206      0.02431     -0.62197   
..           ...          ...          ...          ...          ...   
345     -0.04202      0.83479      0.00123      1.00000      0.12815   
346      0.01361      0.93522      0.04925      0.93159      0.08168   
347      0.03193      0.92489      0.02542      0.92120      0.02242   
348     -0.02099      0.89147     -0.07760      0.82983     -0.17238   
349     -0.15114      0.81147     -0.04822      0.78207     -0.00703   

     Attribute31  Attribute32  Attribute33  Attribute34  
0        0.42267     -0.54487      0.18641     -0.45300  
1       -0.16626     -0.06288     -0.13738     -0.02447  
2        0.60436     -0.24180      0.56045     -0.38238  
3        0.25682      1.00000     -0.32382      1.00000  
4       -0.05707     -0.59573     -0.04608     -0.65697  
..           ...          ...          ...          ...  
345      0.86660     -0.10714      0.90546     -0.04307  
346      0.94066     -0.00035      0.91483      0.04712  
347      0.92459      0.00442      0.92697     -0.00577  
348      0.96022     -0.03757      0.87403     -0.16243  
349      0.75747     -0.06678      0.85764     -0.06151  

[350 rows x 34 columns]

In [38]:
#array
array = X.values
print(array)

point1 = array[0,:]
point2 = array[1,:]
point3 = array[2,:]

#p=1
dist01_2 = np.linalg.norm(point1 - point2,1)
dist01_3 = np.linalg.norm(point1 - point3,1)

#p=2
dist1_2 = np.linalg.norm(point1 - point2)
dist1_3 = np.linalg.norm(point1 - point3)

#p=inf
dist11_2 = np.linalg.norm(point1 - point2,np.inf)
dist11_3 = np.linalg.norm(point1 - point3,np.inf)

#print results
print(dist1_2)
print(dist1_3)
print(dist01_2)
print(dist01_3)
print(dist11_2)
print(dist11_3)

[[ 1.       0.       0.99539 ... -0.54487  0.18641 -0.453  ]
 [ 1.       0.       1.      ... -0.06288 -0.13738 -0.02447]
 [ 1.       0.       1.      ... -0.2418   0.56045 -0.38238]
 ...
 [ 1.       0.       0.94701 ...  0.00442  0.92697 -0.00577]
 [ 1.       0.       0.90608 ... -0.03757  0.87403 -0.16243]
 [ 1.       0.       0.8471  ... -0.06678  0.85764 -0.06151]]
2.7763589251571923
1.1697276018372824
13.080950000000001
5.359709999999999
1.12221
0.45772


In [39]:
# Make matrix distance (50, 50)
def tinh_chuan(dataset): 
    Distance_chuan_1 = np.zeros((50, 50))
    Distance_chuan_2 = np.zeros((50, 50))
    Distance_chuan_vocung = np.zeros((50, 50))
    for i in range(50):
        for j in range(i+1, 50):
            point1 = array[i,:]
            point2 = array[j,:]

            #p=1
            dist01_2 = np.linalg.norm(point1 - point2,1)
            Distance_chuan_1[i][j] = dist01_2
            Distance_chuan_1[j][i] = dist01_2

            #p=2
            dist1_2 = np.linalg.norm(point1 - point2)
            Distance_chuan_2[i][j] = dist1_2
            Distance_chuan_2[j][i] = dist1_2

            #p=inf
            dist11_2 = np.linalg.norm(point1 - point2,np.inf)
            Distance_chuan_vocung[i][j] = dist11_2
            Distance_chuan_vocung[j][i] = dist11_2

    Distance_chuan_1 = pd.DataFrame(Distance_chuan_1)
    Distance_chuan_2 = pd.DataFrame(Distance_chuan_2)
    Distance_chuan_vocung = pd.DataFrame(Distance_chuan_vocung)
    return Distance_chuan_1, Distance_chuan_2, Distance_chuan_vocung

In [40]:
Distanccee_chuan_1, Distance_chuan_2, Distance_chuan_vocung = tinh_chuan(array)
print(Distanccee_chuan_1)
print(Distance_chuan_2)
print(Distance_chuan_vocung)

          0         1         2         3         4         5         6   \
0    0.00000  13.08095   5.35971  21.05729   6.21387  15.16631   7.57704   
1   13.08095   0.00000  15.80038  20.76960  11.52616  12.58796  12.28109   
2    5.35971  15.80038   0.00000  20.30478   8.50424  14.24844  11.57535   
3   21.05729  20.76960  20.30478   0.00000  20.75218  17.81826  24.99635   
4    6.21387  11.52616   8.50424  20.75218   0.00000  11.78266   6.42595   
5   15.16631  12.58796  14.24844  17.81826  11.78266   0.00000  17.61223   
6    7.57704  12.28109  11.57535  24.99635   6.42595  17.61223   0.00000   
7   22.28699  22.63900  21.16584  15.73696  22.27638  15.66824  26.06633   
8    5.81361  16.54506   7.82230  25.08336   9.06074  20.15200   6.56417   
9   17.20169  14.54198  16.08502  19.09482  14.07940   5.57928  19.53089   
10   7.06033  16.56300   9.69796  26.54798  10.21672  21.38354   4.67139   
11  16.25809  23.70878  15.70286  27.23990  19.77926  28.16168  17.94391   
12   6.37224

## Bài 2:

In [41]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import KBinsDiscretizer
from sklearn.preprocessing import StandardScaler

df = pd.read_csv('kddcup.data.corrected', header=None)

print(df)

         0    1     2   3    4      5   6   7   8   9   ...   32   33   34  \
0         0  tcp  http  SF  215  45076   0   0   0   0  ...    0  0.0  0.0   
1         0  tcp  http  SF  162   4528   0   0   0   0  ...    1  1.0  0.0   
2         0  tcp  http  SF  236   1228   0   0   0   0  ...    2  1.0  0.0   
3         0  tcp  http  SF  233   2032   0   0   0   0  ...    3  1.0  0.0   
4         0  tcp  http  SF  239    486   0   0   0   0  ...    4  1.0  0.0   
...      ..  ...   ...  ..  ...    ...  ..  ..  ..  ..  ...  ...  ...  ...   
4898426   0  tcp  http  SF  212   2288   0   0   0   0  ...  255  1.0  0.0   
4898427   0  tcp  http  SF  219    236   0   0   0   0  ...  255  1.0  0.0   
4898428   0  tcp  http  SF  218   3610   0   0   0   0  ...  255  1.0  0.0   
4898429   0  tcp  http  SF  219   1234   0   0   0   0  ...  255  1.0  0.0   
4898430   0  tcp  http  SF  219   1098   0   0   0   0  ...  255  1.0  0.0   

           35    36   37    38   39   40       41  
0        0.

In [42]:
# Kiểm tra giá trị khuyết
print(df.isnull().sum())

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
16    0
17    0
18    0
19    0
20    0
21    0
22    0
23    0
24    0
25    0
26    0
27    0
28    0
29    0
30    0
31    0
32    0
33    0
34    0
35    0
36    0
37    0
38    0
39    0
40    0
41    0
dtype: int64


In [43]:
categorical_columns = df.select_dtypes(include=['object']).columns
print("Categorical attributes:", categorical_columns)
categorical_data = df[categorical_columns]
print("Categorical Data:\n", categorical_data)

Categorical attributes: Index([1, 2, 3, 41], dtype='int64')
Categorical Data:
           1     2   3        41
0        tcp  http  SF  normal.
1        tcp  http  SF  normal.
2        tcp  http  SF  normal.
3        tcp  http  SF  normal.
4        tcp  http  SF  normal.
...      ...   ...  ..      ...
4898426  tcp  http  SF  normal.
4898427  tcp  http  SF  normal.
4898428  tcp  http  SF  normal.
4898429  tcp  http  SF  normal.
4898430  tcp  http  SF  normal.

[4898431 rows x 4 columns]


In [44]:
# Kiểm tra giá trị giống nhau
print(categorical_data.duplicated().sum())
df1 = categorical_data.drop_duplicates()
print("Dữ liệu sau khi xóa những dòng giống nhau:\n", df1)
df1 = df1.reset_index(drop=True)
df1

4897822
Dữ liệu sau khi xóa những dòng giống nhau:
           1         2     3                 41
0        tcp      http    SF           normal.
1288     tcp      http    S2           normal.
1484     tcp      http    S1           normal.
2062     tcp      smtp    SF           normal.
2067     udp  domain_u    SF           normal.
...      ...       ...   ...               ...
4574130  tcp       bgp   REJ          neptune.
4575586  tcp    Z39_50   REJ          neptune.
4578870  tcp      smtp    SF          neptune.
4579297  tcp     other  RSTO          neptune.
4810949  tcp    telnet  RSTO  buffer_overflow.

[609 rows x 4 columns]


1         2     3                 41
0    tcp      http    SF           normal.
1    tcp      http    S2           normal.
2    tcp      http    S1           normal.
3    tcp      smtp    SF           normal.
4    udp  domain_u    SF           normal.
..   ...       ...   ...               ...
604  tcp       bgp   REJ          neptune.
605  tcp    Z39_50   REJ          neptune.
606  tcp      smtp    SF          neptune.
607  tcp     other  RSTO          neptune.
608  tcp    telnet  RSTO  buffer_overflow.

[609 rows x 4 columns]

### Độ đo overlap

In [45]:
from sklearn.neighbors import NearestNeighbors

def overlap_similarity(X, Y):
    d = len(X)  # Số thuộc tính
    w_i = 1 / d  # Trọng số
    similarity= 0
    for i in range(d):
        if X[i] == Y[i]:
            similarity += w_i*1
        else:
            similarity += w_i*0
    
    return similarity

result = overlap_similarity(df1.iloc[0].tolist(), df1.iloc[1].tolist())
print("Độ đo Overlap:", result)

Độ đo Overlap: 0.75


### Độ đo tần suất xuất hiện ngược

In [47]:
from collections import Counter

def inverse_frequency_similarity(X, Y, dataset):
    d = len(X)  # Số thuộc tính
    w_i = 1 / d  # Trọng số

    # Tính tần suất xuất hiện của từng giá trị trong tập dữ liệu
    freq_dicts = []
    for col in range(d):
        col_values = [row[col] for row in dataset]
        freq_dicts.append(Counter(col_values))  # Lưu số lần xuất hiện của từng giá trị

    # Tính độ đo tương đồng
    similarity = 0
    for i in range(d):
        f_xi = freq_dicts[i][X[i]]
        f_yi = freq_dicts[i][Y[i]]
        
        if X[i] == Y[i]:
            S_xi_yi = 1
        else:
            S_xi_yi = 1 / (1 + (np.log(f_xi) * np.log(f_yi))) if f_xi > 0 and f_yi > 0 else 0
        
        similarity += w_i * S_xi_yi
    
    return similarity

result = inverse_frequency_similarity(df1.iloc[0].tolist(), df1.iloc[1].tolist(), df1.values.tolist())
print("Độ đo tần suất xuất hiện ngược:", result)

Độ đo tần suất xuất hiện ngược: 0.7712984101379187
